version: '3.10'

services:
  web:
    build: .
    command: python /haikupost/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/haikupost
    ports:
      - 8000:8000
    depends_on:
      - db
    # environment:
      # - "DJANGO_SECRET_KEY="
      # - "DJANGO_DEBUG=True"
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: 